/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BlockText {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  editor: string;
  html: string | null;
  id: string;
  markdown: string | null;
  sort: number | null;
  status: Generated<string>;
  string: string | null;
  textarea: string | null;
  title: string;
  user_created: string | null;
  user_updated: string | null;
}

export interface Category {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  description: string;
  id: string;
  name: string;
  slug: string;
  sort: number | null;
  status: Generated<string>;
  user_created: string | null;
  user_updated: string | null;
}

export interface DirectusFile {
  charset: string | null;
  created_on: Generated<Timestamp>;
  description: string | null;
  duration: number | null;
  embed: string | null;
  filename_disk: string | null;
  filename_download: string;
  filesize: Int8 | null;
  focal_point_x: number | null;
  focal_point_y: number | null;
  folder: string | null;
  height: number | null;
  id: string;
  location: string | null;
  metadata: Json | null;
  modified_by: string | null;
  modified_on: Generated<Timestamp>;
  storage: string;
  tags: string | null;
  title: string | null;
  tus_data: Json | null;
  tus_id: string | null;
  type: string | null;
  uploaded_by: string | null;
  uploaded_on: Timestamp | null;
  width: number | null;
}

export interface DirectusFolder {
  id: string;
  name: string;
  parent: string | null;
}

export interface DirectusUser {
  appearance: string | null;
  auth_data: Json | null;
  avatar: string | null;
  description: string | null;
  email: string | null;
  email_notifications: Generated<boolean | null>;
  external_identifier: string | null;
  first_name: string | null;
  id: string;
  language: Generated<string | null>;
  last_access: Timestamp | null;
  last_name: string | null;
  last_page: string | null;
  location: string | null;
  password: string | null;
  provider: Generated<string>;
  role: string | null;
  status: Generated<string>;
  tags: Json | null;
  text_direction: Generated<string>;
  tfa_secret: string | null;
  theme_dark: string | null;
  theme_dark_overrides: Json | null;
  theme_light: string | null;
  theme_light_overrides: Json | null;
  title: string | null;
  token: string | null;
}

export interface Footer {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  id: string;
  name: string;
  sort: number | null;
  status: Generated<string>;
  user_created: string | null;
  user_updated: string | null;
}

export interface Image {
  alt: string;
  caption: string | null;
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  id: string;
  local: string | null;
  remote: string | null;
  sort: number | null;
  source: string;
  status: Generated<string>;
  title: string | null;
  user_created: string | null;
  user_updated: string | null;
}

export interface Link {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  href: string;
  icon: string | null;
  icon_color: string | null;
  id: string;
  label: string;
  name: string;
  sort: number | null;
  status: Generated<string>;
  target: Generated<string | null>;
  text: string;
  user_created: string | null;
  user_updated: string | null;
}

export interface Navigation {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  id: string;
  name: string;
  sort: number | null;
  status: Generated<string>;
  user_created: string | null;
  user_updated: string | null;
}

export interface Page {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  description: string;
  id: string;
  path: string;
  sort: number | null;
  status: Generated<string>;
  title: string;
  user_created: string | null;
  user_updated: string | null;
}

export interface Post {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  description: string;
  id: string;
  slug: string;
  sort: number | null;
  status: Generated<string>;
  title: Generated<string>;
  user_created: string | null;
  user_updated: string | null;
}

export interface PostsCategory {
  categories_id: string | null;
  id: Generated<number>;
  posts_id: string | null;
}

export interface PostsTag {
  id: Generated<number>;
  posts_id: string | null;
  tags_id: string | null;
}

export interface Redirect {
  code: string | null;
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  from: string;
  id: string;
  sort: number | null;
  status: Generated<string>;
  to: string;
  user_created: string | null;
  user_updated: string | null;
}

export interface Seo {
  canonical_url: string | null;
  change_frequency: string | null;
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  description: string;
  id: string;
  nofollow: boolean | null;
  noindex: boolean | null;
  priority: number | null;
  sort: number | null;
  status: Generated<string>;
  title: string;
  user_created: string | null;
  user_updated: string | null;
}

export interface Tag {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  description: string;
  id: string;
  name: Generated<string>;
  slug: Generated<string>;
  sort: number | null;
  status: Generated<string>;
  user_created: string | null;
  user_updated: string | null;
}

export interface DB {
  block_text: BlockText;
  categories: Category;
  directus_files: DirectusFile;
  directus_folders: DirectusFolder;
  directus_users: DirectusUser;
  footers: Footer;
  images: Image;
  links: Link;
  navigations: Navigation;
  pages: Page;
  posts: Post;
  posts_categories: PostsCategory;
  posts_tags: PostsTag;
  redirects: Redirect;
  seo: Seo;
  tags: Tag;
}
