export const authors = {
	ankur: {
		databases: ["Postgres", "MySQL", "SQLite", "MongoDB", "Supabase", "Firebase", "Directus"],
		email: "contact@ankur-kumar.in",
		firstName: "Ankur",
		frameworks: [
			"gRPCs",
			"REST API",
			"FastAPI",
			"Echo",
			"Gin",
			"Astro",
			"NextJS",
			"Qwik",
			"TailwindCSS",
			"DaisyUI",
			"Shadcn",
			"MantineUI",
		],
		fullName: "Ankur Kumar",
		image: "https://i.imgur.com/MlFSSy7.png",
		lastName: "Kumar",
		programming: [
			"JavaScript",
			"TypeScript",
			"Python",
			"Golang",
			"Dart",
			"HTML",
			"CSS",
			"Bash",
			"SQL",
		],
		technologies: [
			"Git",
			"Docker",
			"Web Scraping",
			"Linux",
			"Vercel",
			"Cloudflare",
			"Postman",
			"Shell Scripting",
		],
		twitter: "@sirjager",
	},
};
