import {events} from "./events";

export const links = {
	about: {
		color: "#6479F2",
		event: events["clicked-about"],
		href: "/about-me",
		icon: "cib:about-me",
		label: "About Me",
		name: "About",
	},
	blog: {
		color: "#FFA105",
		event: events["clicked-blog"],
		href: "/blog",
		icon: "tabler:brand-blogger",
		label: "Blog",
		name: "Blog",
	},
	discord: {
		color: "#7289DA",
		event: events["clicked-discord"],
		href: "https://discord.gg/XBqUKeE",
		icon: "tabler:brand-discord",
		label: "Join Discord Server",
		name: "Discord Server",
	},
	domain: {
		color: "#6479F2",
		event: events["clicked-domain"],
		href: "ankur-kumar.in",
		icon: "tabler:world-www",
		label: "Visit My Website",
		name: "Ankur Kumar",
	},
	dotfiles: {
		color: "#6e5494",
		event: events["clicked-dotfiles"],
		href: "http://url.ankur-kumar.in/github",
		icon: "tabler:file-code",
		label: "Check out Dotfiles",
		name: "Dotfiles",
	},
	email: {
		color: "#EA4335",
		event: events["clicked-email"],
		href: "mailto:contact@ankur-kumar.in",
		icon: "tabler:mail",
		label: "Email me",
		name: "Email",
	},
	github: {
		color: "#6e5494",
		event: events["clicked-github"],
		href: "http://url.ankur-kumar.in/github",
		icon: "tabler:brand-github",
		label: "Follow on Github",
		name: "Github",
	},
	home: {
		color: "#6479F2",
		event: events["clicked-home"],
		href: "/",
		icon: "tabler:home",
		label: "Home",
		name: "Home",
	},
	instagram: {
		color: "#E1306C",
		event: events["clicked-instagram"],
		href: "http://url.ankur-kumar.in/instagram",
		icon: "tabler:brand-instagram",
		label: "Follow on Instagram",
		name: "Instagram",
	},
	linkedin: {
		color: "#0077B5",
		event: events["clicked-linkedin"],
		href: "http://url.ankur-kumar.in/linkedin",
		icon: "tabler:brand-linkedin",
		label: "Follow on LinkedIn",
		name: "LinkedIn",
	},
	resume: {
		color: "#5AB2FF",
		event: events["clicked-resume"],
		href: "/pdfs/ankur-kumar-resume.pdf",
		icon: "tabler:file-text",
		label: "Download Resume",
		name: "Resume",
		target: "_blank",
	},
	rss: {
		color: "#FB923C",
		event: events["clicked-rssfeed"],
		href: "/rss.xml",
		icon: "tabler:rss",
		label: "Subscribe to RSS",
		name: "RSS",
	},
	sitemap: {
		color: "#135D66",
		event: events["clicked-sitemap"],
		href: "/sitemap-index.xml",
		icon: "tabler:sitemap",
		label: "Check out Sitemap",
		name: "Sitemap",
	},
	twitter: {
		color: "#1da1f2",
		event: events["clicked-twitter"],
		href: "http://url.ankur-kumar.in/x",
		icon: "tabler:brand-x",
		label: "Follow on Twitter",
		name: "Twitter",
	},
	website: {
		color: "#6479F2",
		event: events["clicked-website"],
		href: "https://ankur-kumar.in",
		icon: "tabler:brand-chrome",
		label: "Visit Website",
		name: "Website",
	},
	youtube: {
		color: "#FF0000",
		event: events["clicked-youtube"],
		href: "http://url.ankur-kumar.in/youtube",
		icon: "tabler:brand-youtube",
		label: "Follow on YouTube",
		name: "YouTube",
	},
} as const;

export type MyLink = (typeof links)[keyof typeof links];
